/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'stm32f407IG_demo' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::RTOS&FreeRTOS:Config&FreeRTOS@11.2.0 */
#define RTE_RTOS_FreeRTOS_CONFIG        /* RTOS FreeRTOS Config for FreeRTOS API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.2.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.2.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.2.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.2.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32f4xx.h"


#endif /* RTE_COMPONENTS_H */
