/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'stm32f103' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.1 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::Device:StdPeriph Drivers:FSMC@3.6.0 */
#define RTE_DEVICE_STDPERIPH_FSMC
/* Keil::Device:StdPeriph Drivers:Framework@3.6.0 */
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
/* Keil::Device:StdPeriph Drivers:GPIO@3.6.0 */
#define RTE_DEVICE_STDPERIPH_GPIO
/* Keil::Device:StdPeriph Drivers:RCC@3.6.0 */
#define RTE_DEVICE_STDPERIPH_RCC
/* Keil::Device:StdPeriph Drivers:TIM@3.6.0 */
#define RTE_DEVICE_STDPERIPH_TIM
/* Keil::USB&MDK:CORE@8.0.2 */
#define RTE_USB_Core                    /* USB Core */
/* Keil::USB&MDK:Device:HID@8.0.2 */
#define RTE_USB_Device_HID_0            /* USB Device HID instance 0 */

/* Keil::USB&MDK:Device@8.0.2 */
#define RTE_USB_Device_0                /* USB Device 0 */



#endif /* RTE_COMPONENTS_H */
